// Flat ESLint config for Next.js 16 + ESLint 9.
//
// Next 16 removed `next lint`; we invoke ESLint directly via the `lint`
// script in package.json. `eslint-config-next` v16 exports flat-config
// arrays from both its root and the core-web-vitals subpath.

import nextConfig from "eslint-config-next";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "dist/**",
      "out/**",
      // Generated by Prisma 7 — never lint generated code.
      "node_modules/.prisma/**",
    ],
  },
  ...nextConfig,
  ...nextCoreWebVitals,
  // Suppress anonymous-default-export on the build/config files that
  // genuinely need a literal default export (Next, PostCSS, ESLint itself).
  {
    files: ["**/*.config.{js,mjs,cjs,ts}", "eslint.config.mjs"],
    rules: { "import/no-anonymous-default-export": "off" },
  },
];

export default config;
